12-TP9/src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\TextType;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[UniqueEntity('name')]
#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    #[Assert\Length(min: '2', max: '50')]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive]
    #[Assert\LessThan(1441)]
    private ?int $minute = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive]
    #[Assert\LessThan(51)]
    private ?int $numberOfPer = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive]
    #[Assert\LessThan(6)]
    private ?int $difficulty = null;

    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank]
    private ?string $step_description = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive]
    #[Assert\LessThan(1001)]
    private ?float $price = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $isFavorite = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updateAt = null;

    #[ORM\ManyToMany(targetEntity: Ingredient::class, inversedBy: 'recipes')]
    private Collection $ingredientsList;

    #[ORM\ManyToOne(inversedBy: 'recipes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function __construct()
    {
        $this->ingredientsList = new ArrayCollection();
        $this->createAt = new \DateTimeImmutable();
        $this->updateAt = new \DateTimeImmutable();
    }

    #[ORM\PrePersist]
    public function setUpdatedAtValue()
    {
        $this->updateAt = new \DateTimeImmutable();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMinute(): ?string
    {
        return $this->minute;
    }

    public function setMinute(mixed $minute): self
    {
        $this->minute = $minute;

        return $this;
    }

    public function getNumberOfPer(): ?int
    {
        return $this->numberOfPer;
    }

    public function setNumberOfPer(mixed $numberOfPer): self
    {
        $this->numberOfPer = $numberOfPer;

        return $this;
    }

    public function getDifficulty(): ?string
    {
        return $this->difficulty;
    }

    public function setDifficulty(mixed $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getStepDescription(): ?string
    {
        return $this->step_description;
    }

    public function setStepDescription(string $step_description): self
    {
        $this->step_description = $step_description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(mixed $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIsFavorite(): ?bool
    {
        return $this->isFavorite;
    }

    public function setIsFavorite(bool $favorite): self
    {
        $this->isFavorite = $favorite;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeImmutable $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(?\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredientsList(): Collection
    {
        return $this->ingredientsList;
    }

    public function addIngredientsList(Ingredient $ingredientsList): self
    {
        if (!$this->ingredientsList->contains($ingredientsList)) {
            $this->ingredientsList->add($ingredientsList);
        }

        return $this;
    }

    public function removeIngredientsList(Ingredient $ingredientsList): self
    {
        $this->ingredientsList->removeElement($ingredientsList);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

12-TP9/src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Ingredient;
use App\Entity\Recipe;
use App\Repository\IngredientRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class RecipeType extends AbstractType
{
    private Security $security;

    public function __construct(Security $security){
        $this->security = $security;
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => '2',
                    'maxlength' => '50',
                ],
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 2, 'max' => 50]),
                    new Assert\NotBlank
                ]

            ])
            ->add('minute', IntegerType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'min' => 1,
                    'max' => 1440,
                ],
                'label' => 'Temps (en minutes)',
                'label_attr' => [
                    'class' => 'label-control mt-4',
                ],
                'constraints' => [
                    new  Assert\Positive(),
                    new Assert\LessThan(1441)
                ]
            ])
            ->add('numberOfPer', IntegerType::class, [
                'attr' => [
                    'class' => 'form-range',
                    'min' => 1,
                    'max' => 50,
                ],
                'label' => 'Nombre de personnes',
                'label_attr' => [
                    'class' => 'label-control mt-4',
                ],
                'constraints' => [
                    new  Assert\Positive(),
                    new Assert\LessThan(51)
                ]
            ])
            ->add('difficulty', IntegerType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'min' => 1,
                    'max' => 5,
                ],
                'label' => 'Difficulté',
                'label_attr' => [
                    'class' => 'label-control mt-4',
                ],
                'constraints' => [
                    new  Assert\Positive(),
                    new Assert\LessThan(6)
                ]
            ])
            ->add('step_description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'max' => 300,
                ],
                'label' => 'Etape / Description',
                'label_attr' => [
                    'class' => 'label-control mt-4',
                ],
                'constraints' => [
                    new Assert\NotBlank()
                ]
            ])
            ->add('price', MoneyType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Prix ',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Positive(),
                    new Assert\LessThan(1001)
                ]
            ])
            ->add('isFavorite', CheckboxType::class, [
                'attr' => [
                    'class' => 'form-check-input',
                    ],
                'required' => false,
                'label' => 'Ajouter au favoris',
                'label_attr' => ['class' => 'form-check-label'],
                'constraints' => [
                    new Assert\NotNull()
                ]
            ])
            ->add('ingredientsList', EntityType::class, [
                'attr' => [
                    'class' => 'mx-4'
                ],
                'class' => Ingredient::class,
                'query_builder' => function (IngredientRepository $r){
                    return $r->createQueryBuilder('i')
                        ->where('i.user = :user')
                        ->orderBy('i.name', 'ASC')
                        ->setParameter('user', $this->security->getUser());
                },
                'choice_label' => 'name',
                'label' => 'Les ingrédients',
                'label_attr' => ['class' => 'form-label mt-4'],
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary mt-4'
                ],
                'label' => 'Valider'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

12-TP9/src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\Paginator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecipeController extends AbstractController
{

    /**
     *
     * This controller display all recipes
     * @author Alexandre Messuve <alexandre.messuves@gmail.com>
     * @param PaginatorInterface $paginator
     * @param RecipeRepository $repository
     * @param Request $request
     * @return Response
     */
    #[Route('/recette', name: 'recipe.index', methods: ['GET'])]
    public function index(PaginatorInterface $paginator, RecipeRepository $repository, Request $request): Response
    {
        $currentUser = $this->getUser();
        $recipes = $paginator->paginate(
            $repository->findBy(['user' => $currentUser]),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('/pages/recipe/index.html.twig', [
            'recipes' => $recipes,
            'currentUser' => $currentUser
        ]);
    }


    /**
     * This controller create a recipe
     * @author Alexandre Messuve <alexandre.messuves@gmail.com>
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route("/recette/ajout", name:"recipe.new" , methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $currentUser = $this->getUser();
        $recipe = new Recipe();
        $form =  $this->createForm(RecipeType::class, $recipe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();
            $recipe->setUser($currentUser);

            $manager->persist($recipe);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre recette a bien été ajouté'
            );
            return $this->redirectToRoute('recipe.index');
        }

        return $this->render('/pages/recipe/new.html.twig', [
            'form' => $form->createView(),
            'currentUser' => $currentUser
        ]);
    }

    /**
     * Controller update a recipe
     * @param Request $request
     * @param Recipe $recipe
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/recette/modifier/{id}', name:'recipe.edit', methods: ['GET', 'POST'])]
    public function edit(
        Request $request,
        Recipe $recipe,
        EntityManagerInterface $manager
    ): Response
    {
        $currentUser = $this->getUser();
        $form = $this->createForm(RecipeType::class, $recipe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $recipe = $form->getData();
            $manager->persist($recipe);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre recette a bien été mis a jour'
            );

            return $this->redirectToRoute('recipe.index');
        }

        return $this->render('/pages/recipe/edit.html.twig', [
            'form' => $form->createView(),
            'currentUser' => $currentUser
        ]);
    }

    #[Route('/recette/supprimer/{id}', name: 'recipe.del', methods: ['GET'])]
    public function delete(EntityManagerInterface $manager, Recipe $recipe): Response
    {
        $manager->remove($recipe);
        $manager->flush();

        $this->addFlash(
            'success',
            'Ingrédient a bien été supprimé'
        );

        return $this->redirectToRoute('recipe.index');
    }
}

12-TP9/templates/pages/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1 class="mt-4">Mise a jour de la recette</h1>
        {{ form_start(form) }}

        <div class="form-group">
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
            <div class="form-error">
                {{ form_errors(form.name) }}
            </div>

        </div>
        <div class="form-group">
            {{ form_label(form.minute) }}
            {{ form_widget(form.minute) }}
            <div class="form-error">
                {{ form_errors(form.minute) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.numberOfPer) }}
            {{ form_widget(form.numberOfPer) }}
            <div class="form-error">
                {{ form_errors(form.numberOfPer) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.difficulty) }}
            {{ form_widget(form.difficulty) }}
            <div class="form-error">
                {{ form_errors(form.difficulty) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.step_description) }}
            {{ form_widget(form.step_description) }}
            <div class="form-error">
                {{ form_errors(form.step_description) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.price) }}
            {{ form_widget(form.price) }}
            <div class="form-error">
                {{ form_errors(form.price) }}
            </div>
        </div>

        <div class="form-group">
            {{ form_label(form.isFavorite) }}
            {{ form_widget(form.isFavorite) }}
            <div class="form-error">
                {{ form_errors(form.isFavorite) }}
            </div>
        </div>

        {{ form_row(form.ingredientsList) }}

        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>


        {{ form_end(form) }}
    </div>

{% endblock %}

12-TP9/templates/pages/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes recettes{% endblock %}

{% block body %}
    <div class="container mt-4">
        {% if not recipes.items is same as ([]) %}
            {% for message in app.flashes('success') %}
                <div class="text-center alert alert-dismissible  alert-success mt-4">
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}
            <h1 class="text-center mb-4">Mes Recettes({{ recipes | length }})</h1>
            <div class="text-center">
                <a href="{{ path('recipe.new') }}" class="btn btn-success ">Ajouter une recette</a>
            </div>
            <div class="d-flex flex-wrap align-items-stretch mt-5">
                {% for recipe in recipes %}
                    <div class="card mt-5 mx-2" style="height: auto; width: 400px " >
                        <img class="card-img-top" height="80px"  width="400px" src="" alt="img">
                        <div class="card-body d-flex flex-column">
                            <h6 class="card-subtitle mb-2 text-muted align-content-end">Ajouté {{ recipe.createAt | ago(locale='fr')}} €</h6>
                            {% if not recipe.updateAt | ago() is same as (recipe.createAt | ago()) %}
                                <h6 class="card-subtitle mb-2 text-muted align-content-end">Mis a jour {{ recipe.updateAt | ago(locale='fr')}} €</h6>
                            {% endif %}
                            <h4 class="card-title text-center">{{ recipe.name }}</h4>
                            <h6 class="card-subtitle mb-2 text-muted text-center">
                                Pour: {{ recipe.numberOfPer}} personne.<br>

                                Cout: {{ recipe.price }} €
                            </h6>
                            <p class="card-text">
                                Ingredients:<br>-{{ recipe.ingredientslist| join('<br> -') }}<br>Description :<br>{{ recipe.stepDescription }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{ path('recipe.edit', {id: recipe.id} ) }}" class="btn btn-outline-info ms-auto">Modifier</a>
                            <a onclick="return confirm('Voulez vous vraiment supprimer la recette ? ')" href="{{ path('recipe.del', {id: recipe.id} ) }}" class="btn btn-outline-danger me-auto">Supprimer</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="navigation d-flex justify-content-center mt-4">
                {{ knp_pagination_render(recipes) }}
            </div>
        {% else %}
            {% for message in app.flashes('success') %}
                <div class="text-center alert alert-dismissible  alert-success mt-4">
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}
            <h4 class="text-center">Vous n'avez pas de recette</h4>
            <div class="text-center">
                <a href="{{ path('recipe.new') }}" class="btn btn-success ">Ajouter une recette</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

12-TP9/templates/pages/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1 class="mt-4">Création d'une recette</h1>
        {{ form_start(form) }}

        <div class="form-group">
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
            <div class="form-error">
                {{ form_errors(form.name) }}
            </div>

        </div>
        <div class="form-group">
            {{ form_label(form.minute) }}
            {{ form_widget(form.minute) }}
            <div class="form-error">
                {{ form_errors(form.minute) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.numberOfPer) }}
            {{ form_widget(form.numberOfPer) }}
            <div class="form-error">
                {{ form_errors(form.numberOfPer) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.difficulty) }}
            {{ form_widget(form.difficulty) }}
            <div class="form-error">
                {{ form_errors(form.difficulty) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.step_description) }}
            {{ form_widget(form.step_description) }}
            <div class="form-error">
                {{ form_errors(form.step_description) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.price) }}
            {{ form_widget(form.price) }}
            <div class="form-error">
                {{ form_errors(form.price) }}
            </div>
        </div>

        <div class="form-group">
            {{ form_label(form.isFavorite) }}
            {{ form_widget(form.isFavorite) }}
            <div class="form-error">
                {{ form_errors(form.isFavorite) }}
            </div>
        </div>

        {{ form_row(form.ingredientsList) }}

        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>


        {{ form_end(form) }}
    </div>

{% endblock %}